In [2]:
import numpy as np

ones2 = np.ones((3,5,3))
print(ones2)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [4]:
print(ones2.shape)

(3, 5, 3)


In [5]:
print(ones2.ndim)

3


In [ ]:
print(ones2.size) #num of elements

45


In [7]:
print(ones2.dtype)

float64
