In [36]:
import numpy as np

arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


In [24]:
reshaped = arr.reshape((2,3))
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [26]:
#flatten
flattended = reshaped.flatten()
print(flattended)

[0 1 2 3 4 5]


In [30]:
#transpose 
transpose = reshaped.T
print(f"reshaped :\n{reshaped}")
print(f"transpose :\n{transpose}")

reshaped :
[[0 1 2]
 [3 4 5]]
transpose :
[[0 3]
 [1 4]
 [2 5]]


In [39]:
import numpy as np

arr = np.arange(6)
print("Original array:", arr)

arr.resize(8) # in-place
print("After resize:", arr)


Original array: [0 1 2 3 4 5]
After resize: [0 1 2 3 4 5 0 0]
