In [ ]:
import numpy as np
arr = np.arange(11)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10]
[3 4]


In [6]:
#slice

sliced = arr[0:10:2]
print(sliced)

[0 2 4 6 8]


In [7]:
print(arr[-1])

10


In [ ]:
#2d array

array_2d = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

print(array_2d)

print(f"access specific : {array_2d[1,2]}")
print(f"access specific : {array_2d[1]}") #1st row
print(f"access specific : {array_2d[:,2]}") #2nd col



[[1 2 3]
 [4 5 6]
 [7 8 9]]
access specific : 6
access specific : [4 5 6]
access specific : [3 6 9]


In [17]:
arr = np.array([1,2,3,4,2,3,4,3,4,5])
sorted = np.sort(arr)
print(sorted)

[1 2 2 3 3 3 4 4 4 5]


In [20]:
#sorted 2d

arr2d = np.array([[1,2,3],
                  [3,2,1],
                  [4,5,6]])
sorted = np.sort(arr2d , axis=0)
sorted1 = np.sort(arr2d , axis=1)

print(f"sorted \n {sorted}")
print(f"sorted1 \n {sorted1}")



sorted 
 [[1 2 1]
 [3 2 3]
 [4 5 6]]
sorted1 
 [[1 2 3]
 [1 2 3]
 [4 5 6]]


In [23]:
argsorted = np.argsort(arr2d[:,1])
print(argsorted)

[0 1 2]


In [30]:
#filtering
numbers = np.array([1,2,3,1,2,3,6,7,8,5,7])
even = numbers[numbers %2 ==0]
print(even)

[2 2 6 8]


In [ ]:
mask = numbers > 5
print(mask)
where_res = np.where(mask)
print(where_res)
print(np.where(mask))

[6 7 8 7]
(array([ 6,  7,  8, 10]),)
(array([ 6,  7,  8, 10]),)
